apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
- count: 1
  name: frontend

images:
- name: frontend
  newName: 983460235393.dkr.ecr.ap-northeast-2.amazonaws.com/ssh-frontend
  newTag: latest

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: frontend
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: frontend-config

configMapGenerator:
- name: frontend-config
  literals:
  - REACT_APP_API_BASE_URL=http://k8s-backend-backendi-a93a4f8fff-54169154.ap-northeast-2.elb.amazonaws.com
