apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: rollout-resource-patch.yaml
    target:
      kind: Rollout
      name: backend
  - path: replica-patch.yaml
    target:
      kind: Rollout
      name: backend
  - path: image-patch.yaml
    target:
      kind: Rollout
      name: backend
