apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: backend
    count: 1

images:
  - name: backend
    newName: 983460235393.dkr.ecr.ap-northeast-2.amazonaws.com/ssh-backend
    newTag: "0.1.0"
